### ISSUE TITLE
開発環境の準備

### ISSUE THREAD

**Issue by mayok** [clom/Jmdwiki#2]

**Comment by mayok** [comment]
OS X での手順は，http://qiita.com/yukihirai0505/items/144bd4659bd904afae22
が参考になりました

IntelliJの導入 はしなくて良いです

**Comment by mayok** [comment]
開発環境が整ったら，ここで or Slack で報告してください

(例: おわりましたー )

**Comment by clom** [comment]
done

**Comment by yuji61** [comment]
おそらく出来ました。おそらく。

**Comment by mayok** [comment]
みんな開発環境作り終わった :)
