### ISSUE TITLE
マイグレートファイルの作成

### ISSUE THREAD

**Issue by mayok** [clom/Jmdwiki#5]
http://qiita.com/dahugani/items/bb0bbd8fb263bc19cc57
- マイグレートファイル作成
- マイグレートの実行

を参考にする

**Comment by clom** [comment]
Pull Request #17

**Comment by clom** [comment]
http://qiita.com/rubytomato@github/items/17aed34b6294b4f205ea#%E9%9B%9B%E5%BD%A2%E3%81%AE%E7%94%9F%E6%88%90

そもそも bean を作成すればマイグレーションファイルを作成しなくても良いのではという説もある。
