### ISSUE TITLE
markdown を html に変換する javascript の選定

### ISSUE THREAD

**Issue by mayok** [clom/Jmdwiki#6]

**Comment by mayok** [comment]
markdown を html に変換する javascript はいくつか種類があるので，
担当者はここで紹介してしてください

**Comment by mayok** [comment]
- markdown-js https://github.com/evilstreak/markdown-js
- Marked.js https://github.com/chjj/marked
- showdown https://github.com/showdownjs/showdown

などがあります．

どんな特徴があるのか，使いやすさなどを調べて，どれにするかを決めてください

**Comment by yuji61** [comment]
http://kannokanno.hatenablog.com/entry/2013/06/19/132042
私はMarkdownもJavascriptも書いたことがないので、あまり細かいところはわからないのですが、ここによると、https://github.com/chjj/marked
が一番制約が少なくて使いやすいようです。

**Comment by mayok** [comment]
ありがとうございます

では，今回は marked を使うことにしましょう
